server:
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active:
    - prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,*.jsp,*.php,*.jsf,*.asp,*.html.*.pl,*.txt,*.sh,/scrips/*"
        session-stat-enable: false
  aop:
    proxy-target-class: true
  application:
    name: BASEINFO-SERVICE
  mvc:
    favicon:
      enabled: false
    ignore-default-model-on-redirect: true
    throw-exception-if-no-handler-found: true


