server:
  port: 8085
spring:
  mvc:
    async:
      request-timeout: 15000
  datasource:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 123456
